version: "3.9"
services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/mailer
    command: bundle exec ./bin/mailer run
    platform: linux/amd64
