keychain:
  barong:
    algorithm: RS256
    value: "<%= ENV['BARONG_JWT_PUBLIC_KEY'] %>"
  peatio:
    algorithm: RS256
    value: "<%= ENV['PEATIO_JWT_PUBLIC_KEY'] %>"
  p2p:
    algorithm: RS256
    value: "<%= ENV['P2P_JWT_PUBLIC_KEY'] %>"

exchanges:
  barong_system:
    name: barong.events.system
    signer: barong
  barong_model:
    name: barong.events.model
    signer: barong
  peatio:
    name: peatio.events.model
    signer: peatio
  p2p:
    name: p2p.events.email
    signer: p2p

events:
  - name: Welcome Email
    key: user.email.welcome
    exchange: barong_system
    templates:
      en:
        subject: Welcome to the Bitzlato family!
        template_path: welcome_email
      ru:
        subject: Добро пожаловать в семью Bitzlato!
        template_path: welcome_email

  - name: Email Confirmation
    key: user.email.confirmation.token
    exchange: barong_system
    templates:
      en:
        subject: Registration Confirmation
        template_path: email_confirmation
      ru:
        subject: Подтверждение Регистрации
        template_path: email_confirmation

  - name: Password Reset
    key: user.password.reset.token
    exchange: barong_system
    templates:
      en:
        subject: Password Reset
        template_path: password_reset
      ru:
        subject: Сброс Пароля
        template_path: password_reset

  - name: Password Changed
    key: user.password.change
    exchange: barong_system
    templates:
      en:
        subject: Password Changed
        template_path: password_changed
      ru:
        subject: Пароль Изменен
        template_path: password_changed

  - name: 2FA Activated
    key: label.created
    expression:
      and:
        record.key: "otp"
    exchange: barong_model
    templates:
      en:
        subject: "[Bitzlato Exchange] 2FA Activated"
        template_path: 2fa_activated
      ru:
        subject: "[Bitzlato Exchange] 2FA активирована"
        template_path: 2fa_activated

  - name: Label Updated
    key: label.updated
    exchange: barong_model
    templates:
      en:
        subject: Label Updated
        template_path: label
      ru:
        subject: Ярлык обновлен
        template_path: label

  - name: Session Create
    key: session.create
    exchange: barong_system
    templates:
      en:
        subject: New Login
        template_path: session_create
      ru:
        subject: Новый вход
        template_path: session_create

  - name: User Verification Approved
    key: user.verification_approved
    exchange: barong_system
    templates:
      en:
        subject: Your application for verification in Bitzlato has been approved!
        template_path: user_verification_approved
      ru:
        subject: Ваша заявка на верификацию в Bitzlato одобрена!
        template_path: user_verification_approved

  - name: User Verification Rejected
    key: user.verification_rejected
    exchange: barong_system
    templates:
      en:
        subject: Verification Rejected
        template_path: user_verification_rejected
      ru:
        subject: Верификация Отклонена
        template_path: user_verification_rejected

  - name: Deposit Updated
    key: deposit.updated
    exchange: peatio
    templates:
      en:
        subject: Deposit Updated
        template_path: deposit_updated
      ru:
        subject: Депозит обновлен
        template_path: deposit_updated

  - name: Withdrawal Succeed
    key: withdraw.updated
    expression:
      and:
        record.state: 'succeed'
    exchange: peatio
    templates:
      en:
        subject: Withdrawal Succeed
        template_path: withdraw_updated
      ru:
        subject: Вывод средств выполнен успешно
        template_path: withdraw_updated

  - name: Withdrawal Rejected
    key: withdraw.updated
    expression:
      and:
        record.state: 'rejected'
    exchange: peatio
    templates:
      en:
        subject: Withdrawal Rejected
        template_path: withdraw_updated
      ru:
        subject: Вывод средств отклонен
        template_path: withdraw_updated

  - name: Withdrawal Canceled
    key: withdraw.updated
    expression:
      and:
        record.state: 'canceled'
    exchange: peatio
    templates:
      en:
        subject: Withdrawal Canceled
        template_path: withdraw_updated
      ru:
        subject: Вывод средств отменен
        template_path: withdraw_updated

  - name: Withdrawal Failed
    key: withdraw.updated
    expression:
      and:
        record.state: 'failed'
    exchange: peatio
    templates:
      en:
        subject: Withdrawal Failed
        template_path: withdraw_updated
      ru:
        subject: Вывод не выполнен
        template_path: withdraw_updated

  - name: Withdrawal Errored
    key: withdraw.updated
    expression:
      and:
        record.state: 'errored'
    exchange: peatio
    templates:
      en:
        subject: Withdrawal Errored
        template_path: withdraw_updated
      ru:
        subject: Ошибка при выводе
        template_path: withdraw_updated

  - name: New Beneficiary
    key: beneficiary.created
    exchange: peatio
    templates:
      en:
        subject: New Beneficiary
        template_path: new_beneficiary
      ru:
        subject: Новый бенефициар
        template_path: new_beneficiary

  - name: Beneficiary Pin Resend
    key: beneficiary.updated
    expression:
      not:
        changes.pin: null
    exchange: peatio
    templates:
      en:
        subject: Beneficiary Pin
        template_path: beneficiary_pin
      ru:
        subject: Пин-код бенефициарa
        template_path: beneficiary_pin

  - name: API key registration
    key: api_key.registration
    exchange: p2p
    templates:
      en:
        subject: API key registration
        template_path: p2p/api_key_registration
      ru:
        subject: Создание API ключа
        template_path: p2p/api_key_registration

  - name: Withdrawal request
    key: withdrawal.request
    exchange: p2p
    templates:
      en:
        subject: Withdrawal request
        template_path: p2p/withdrawal_request
      ru:
        subject: Запрос Вывода
        template_path: p2p/withdrawal_request

  - name: Voucher creation
    key: voucher.creation
    exchange: p2p
    templates:
      en:
        subject: Voucher creation
        template_path: p2p/voucher_creation
      ru:
        subject: Создание Чека
        template_path: p2p/voucher_creation


  # expression example
  # - name: Session Create
  #   key: session.create
  #   expression:
  #     and:                          # need to use and/or/not operator here
  #       record.user_ip: '::1'       # full patch to key
  #       record.user.role: 'member'
  #   exchange: barong_system
  #   templates:
  #     en:
  #       subject: New Login
  #       template_path: session_create
